Repository woori-design/Woori-Design-System, pull requests merged in 2025-04, with the labels that each got.

#2 feat: 스토리북 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  package-lock.json
  package.json
  src/libs/button/Button.mdx
  src/libs/button/Button.stories.tsx
  src/libs/button/Button.tsx
  src/libs/button/Button.type.ts
Labels: feature

#4 feat: color foundation 작업
  src/libs/button/Button.mdx
  src/libs/button/Button.stories.tsx
  src/libs/button/Button.tsx
  src/styles/colors.css
  src/styles/foundation/color/color.mdx
  src/styles/foundation/color/color.stories.tsx
  src/styles/foundation/color/primitiveColor/primitiveColor.ts
  src/styles/foundation/color/primitiveColor/primitiveColor.type.ts
  src/styles/foundation/color/semanticColor/semanticColor.ts
  src/styles/foundation/color/semanticColor/semanticColor.type.ts
  src/styles/index.css
  src/styles/spacing.css
  src/styles/theme/theme.tsx
  src/styles/theme/theme.type.ts
  src/styles/typography.css
Labels: feature

#6 feat: typography foundation 작업
  src/styles/foundation/typography/typography.mdx
  src/styles/foundation/typography/typography.stories.tsx
  src/styles/foundation/typography/typography.ts
  src/styles/foundation/typography/typography.type.ts
  src/styles/theme/theme.tsx
  src/styles/theme/theme.type.ts
Labels: feature

#9 feat: Gray Color Foundation 추가
  src/styles/foundation/color/primitiveColor/primitiveColor.ts
  src/styles/foundation/color/primitiveColor/primitiveColor.type.ts
  src/styles/foundation/color/semanticColor/semanticColor.ts
  src/styles/foundation/color/semanticColor/semanticColor.type.ts
Labels: feature

#14 fix: 빌드 및 배포 방식 변경
  package.json
  src/App.tsx
  src/index.css
  src/index.ts
  vite.config.ts
Labels: bug, enhancement

#21 feat: 스토리북 테마 변경 작업
  .storybook/manager.js
  package-lock.json
  package.json
  public/woori-design-circle.png
  public/woori-design-logo.png
Labels: feature

#11 update: Switch 컴포넌트 고도화 및 스토리북 반영
  package-lock.json
  package.json
  src/libs/switch/Switch.mdx
  src/libs/switch/Switch.module.css
  src/libs/switch/Switch.stories.tsx
  src/libs/switch/Switch.tsx
  src/libs/switch/Switch.type.ts
  src/libs/switch/index.ts
  src/styles/foundation/typography/typography.ts
  src/styles/foundation/typography/typography.type.ts
Labels: enhancement

#18 feat: 버튼 컴포넌트 리뉴얼 작업
  src/libs/button/Button.mdx
  src/libs/button/Button.module.css
  src/libs/button/Button.stories.tsx
  src/libs/button/Button.tsx
  src/libs/button/Button.type.ts
Labels: feature

#13 refactor: Divider 컴포넌트 리팩토링 및 Storybook 문서 작성
  src/index.ts
  src/libs/divider/Divider.mdx
  src/libs/divider/Divider.stories.tsx
  src/libs/divider/Divider.tsx
  src/libs/divider/Divider.type.ts
  src/libs/divider/divider.module.css
  src/libs/divider/divider.tsx
Labels: documentation, enhancement
